apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-php-laravel
spec:
  secretName: tls-php-laravel
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - php-laravel.jx-interview.k8s.trunksys.com
